services:
   frontend:
     build:
       context: ./client
     ports:
      - "5173:5173"
     environment:
       VITE_API_URL: http://localhost:3000
       VITE_SUPABASE_URL: 
       VITE_SUPABASE_ANON_KEY: 

   backend:
     build:
      context: ./
     ports:
      - "3000:3000" 
     environment:
        NODE_ENV: development
        FRED_API_KEY: 
        CURRENCY_API_KEY: 
        GEMINI_API_KEY: 
        SUPABASE_URL: 
        SUPABASE_SERVICE_ROLE_KEY: 
        PORT: 3000